# Data Manipulation

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_csv('titanic_train.csv')

In [3]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [6]:
df.tail(5)

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [7]:
df['Survived'].unique()  #Similarly you can check any column unique values

array([0, 1], dtype=int64)

In [8]:
df['SibSp'].unique() 

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [9]:
df['Pclass'].unique() 

array([3, 1, 2], dtype=int64)

# How to rename categoriesmusing pandas method

In [12]:
df_new=pd.Categorical(df['Survived'])

df_new= df_new.rename_categories(['Died','Survived'])


df_new.describe()

counts     freqs
categories                  
Died           549  0.616162
Survived       342  0.383838

In [30]:
Pclass_New = pd.Categorical(df['Pclass'], ordered=True)


Pclass_New=Pclass_New.rename_categories(['First_class','Second_class','Third_class'])


Pclass_New.describe()

counts     freqs
categories                    
First_class      216  0.242424
Second_class     184  0.206510
Third_class      491  0.551066

In [29]:
New_s=pd.Categorical(df['SibSp'], ordered=True)

New_s=New_s.rename_categories(['T1','T2','T3','T4','T5','T6','T7'])

New_s.describe()

counts     freqs
categories                  
T1             608  0.682379
T2             209  0.234568
T3              28  0.031425
T4              16  0.017957
T5              18  0.020202
T6               5  0.005612
T7               7  0.007856

In [31]:
#Reassign New name to Pclass


df['Pclass']=Pclass_New

In [33]:
#Check if they have changed

df.head(10)

PassengerId  Survived        Pclass  \
0            1         0   Third_class   
1            2         1   First_class   
2            3         1   Third_class   
3            4         1   First_class   
4            5         0   Third_class   
5            6         0   Third_class   
6            7         0   First_class   
7            8         0   Third_class   
8            9         1   Third_class   
9           10         1  Second_class   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [34]:
df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [36]:
char_Cabin= df['Cabin'].astype(str)  #conver data to string
#List comprehension (creating list using another set of string, list etc)

New_Cabin = np.array([Cabin[0] for Cabin in char_Cabin]) # Take first letter

New_Cabin = pd.Categorical(New_Cabin)

New_Cabin.describe()

counts     freqs
categories                  
A               15  0.016835
B               47  0.052750
C               59  0.066218
D               33  0.037037
E               32  0.035915
F               13  0.014590
G                4  0.004489
T                1  0.001122
n              687  0.771044

In [37]:
df['Cabin']=New_Cabin  #Reassign names to cabin

In [42]:
df.head(18)

PassengerId  Survived        Pclass  \
0             1         0   Third_class   
1             2         1   First_class   
2             3         1   Third_class   
3             4         1   First_class   
4             5         0   Third_class   
5             6         0   Third_class   
6             7         0   First_class   
7             8         0   Third_class   
8             9         1   Third_class   
9            10         1  Second_class   
10           11         1   Third_class   
11           12         1   First_class   
12           13         0   Third_class   
13           14         0   Third_class   
14           15         0   Third_class   
15           16         1  Second_class   
16           17         0   Third_class   
17           18         1  Second_class   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                               Rice, Master. Eugene    male   2.0      4   
17                       Williams, Mr. Charles Eugene    male   NaN      0   

    Parch            Ticket     Fare Cabin Embarked  
0       0         A/5 21171   7.2500     n        S  
1       0          PC 17599  71.2833     C        C  
2       0  STON/O2. 3101282   7.9250     n        S  
3       0            113803  53.1000     C        S  
4       0            373450   8.0500     n        S  
5       0            330877   8.4583     n        Q  
6       0             17463  51.8625     E        S  
7       1            349909  21.0750     n        S  
8       2            347742  11.1333     n        S  
9       0            237736  30.0708     n        C  
10      1           PP 9549  16.7000     G        S  
11      0            113783  26.5500     C        S  
12      0         A/5. 2151   8.0500     n        S  
13      5            347082  31.2750     n        S  
14      0            350406   7.8542     n        S  
15      0            248706  16.0000     n        S  
16      1            382652  29.1250     n        Q  
17      0            244373  13.0000     n        S

In [40]:
df.shape

(891, 12)

# Find all passengers whose age is missing

In [43]:
## np.where gives the index of those missing data

In [44]:
missing = np.where(df['Age'].isnull()==True) #Find all nulls in column Age

missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dt

In [45]:
#Using the index, locate passangers

df.loc[missing]

PassengerId  Survived        Pclass  \
5              6         0   Third_class   
17            18         1  Second_class   
19            20         1   Third_class   
26            27         0   Third_class   
28            29         1   Third_class   
..           ...       ...           ...   
859          860         0   Third_class   
863          864         0   Third_class   
868          869         0   Third_class   
878          879         0   Third_class   
888          889         0   Third_class   

                                         Name     Sex  Age  SibSp  Parch  \
5                            Moran, Mr. James    male  NaN      0      0   
17               Williams, Mr. Charles Eugene    male  NaN      0      0   
19                    Masselmani, Mrs. Fatima  female  NaN      0      0   
26                    Emir, Mr. Farred Chehab    male  NaN      0      0   
28              O'Dwyer, Miss. Ellen "Nellie"  female  NaN      0      0   
..                                        ...     ...  ...    ...    ...   
859                          Razi, Mr. Raihed    male  NaN      0      0   
863         Sage, Miss. Dorothy Edith "Dolly"  female  NaN      8      2   
868               van Melkebeke, Mr. Philemon    male  NaN      0      0   
878                        Laleff, Mr. Kristo    male  NaN      0      0   
888  Johnston, Miss. Catherine Helen "Carrie"  female  NaN      1      2   

         Ticket     Fare Cabin Embarked  
5        330877   8.4583     n        Q  
17       244373  13.0000     n        S  
19         2649   7.2250     n        C  
26         2631   7.2250     n        C  
28       330959   7.8792     n        Q  
..          ...      ...   ...      ...  
859        2629   7.2292     n        C  
863    CA. 2343  69.5500     n        S  
868      345777   9.5000     n        S  
878      349217   7.8958     n        S  
888  W./C. 6607  23.4500     n        S  

[177 rows x 12 columns]

# Find the maximuim fare 

In [46]:
index = np.where(df['Fare'] == max(df['Fare']))

index

(array([258, 679, 737], dtype=int64),)

In [48]:
df.loc[index]

PassengerId  Survived       Pclass                                Name  \
258          259         1  First_class                    Ward, Miss. Anna   
679          680         1  First_class  Cardeza, Mr. Thomas Drake Martinez   
737          738         1  First_class              Lesurer, Mr. Gustave J   

        Sex   Age  SibSp  Parch    Ticket      Fare Cabin Embarked  
258  female  35.0      0      0  PC 17755  512.3292     n        C  
679    male  36.0      0      1  PC 17755  512.3292     B        C  
737    male  35.0      0      0  PC 17755  512.3292     B        C

In [49]:
inde = np.where(df['Fare'] == min(df['Fare']))

inde

(array([179, 263, 271, 277, 302, 413, 466, 481, 597, 633, 674, 732, 806,
        815, 822], dtype=int64),)

In [50]:
df.loc[inde]

PassengerId  Survived        Pclass                              Name  \
179          180         0   Third_class               Leonard, Mr. Lionel   
263          264         0   First_class             Harrison, Mr. William   
271          272         1   Third_class      Tornquist, Mr. William Henry   
277          278         0  Second_class       Parkes, Mr. Francis "Frank"   
302          303         0   Third_class   Johnson, Mr. William Cahoone Jr   
413          414         0  Second_class    Cunningham, Mr. Alfred Fleming   
466          467         0  Second_class             Campbell, Mr. William   
481          482         0  Second_class  Frost, Mr. Anthony Wood "Archie"   
597          598         0   Third_class               Johnson, Mr. Alfred   
633          634         0   First_class     Parr, Mr. William Henry Marsh   
674          675         0  Second_class        Watson, Mr. Ennis Hastings   
732          733         0  Second_class              Knight, Mr. Robert J   
806          807         0   First_class            Andrews, Mr. Thomas Jr   
815          816         0   First_class                  Fry, Mr. Richard   
822          823         0   First_class   Reuchlin, Jonkheer. John George   

      Sex   Age  SibSp  Parch  Ticket  Fare Cabin Embarked  
179  male  36.0      0      0    LINE   0.0     n        S  
263  male  40.0      0      0  112059   0.0     B        S  
271  male  25.0      0      0    LINE   0.0     n        S  
277  male   NaN      0      0  239853   0.0     n        S  
302  male  19.0      0      0    LINE   0.0     n        S  
413  male   NaN      0      0  239853   0.0     n        S  
466  male   NaN      0      0  239853   0.0     n        S  
481  male   NaN      0      0  239854   0.0     n        S  
597  male  49.0      0      0    LINE   0.0     n        S  
633  male   NaN      0      0  112052   0.0     n        S  
674  male   NaN      0      0  239856   0.0     n        S  
732  male   NaN      0      0  239855   0.0     n        S  
806  male  39.0      0      0  112050   0.0     A        S  
815  male   NaN      0      0  112058   0.0     B        S  
822  male  38.0      0      0   19972   0.0     n        S

# Find the family who has highest members?

In [58]:
#Sibsp and parch are siblings and parents/guardian respectively (add both of the and create new column)


df['Family'] = df['SibSp'] + df['Parch']


most_family = np.where(df["Family"] == max(df["Family"]))

df.loc[most_family]

PassengerId  Survived       Pclass                               Name  \
159          160         0  Third_class         Sage, Master. Thomas Henry   
180          181         0  Third_class       Sage, Miss. Constance Gladys   
201          202         0  Third_class                Sage, Mr. Frederick   
324          325         0  Third_class           Sage, Mr. George John Jr   
792          793         0  Third_class            Sage, Miss. Stella Anna   
846          847         0  Third_class           Sage, Mr. Douglas Bullen   
863          864         0  Third_class  Sage, Miss. Dorothy Edith "Dolly"   

        Sex  Age  SibSp  Parch    Ticket   Fare Cabin Embarked  Family  
159    male  NaN      8      2  CA. 2343  69.55     n        S      10  
180  female  NaN      8      2  CA. 2343  69.55     n        S      10  
201    male  NaN      8      2  CA. 2343  69.55     n        S      10  
324    male  NaN      8      2  CA. 2343  69.55     n        S      10  
792  female  NaN      8      2  CA. 2343  69.55     n        S      10  
846    male  NaN      8      2  CA. 2343  69.55     n        S      10  
863  female  NaN      8      2  CA. 2343  69.55     n        S      10