In [1]:
import tensorflow as tf

In [2]:
hello_constant=tf.constant('Hello world!')

hello_constant

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello world!'>

In [3]:
import tensorflow.compat.v1 as tf
sess = tf.Session()

In [4]:
import tensorflow as tf

tf.compat.v1.disable_eager_execution()

a = tf.constant(5)
b = tf.constant(6)
c = tf.constant(7)
d = tf.multiply(a,b)
e = tf.add(c,d)
f = tf.subtract(a,c)

with tf.compat.v1.Session() as sess:
  outs = sess.run(f)
  print(outs)

-2


In [5]:
import tensorflow as tf

tf.compat.v1.disable_eager_execution()

hello_constant=tf.constant('Hello world!')

with tf.compat.v1.Session() as sess:
    
    output=sess.run(hello_constant)
    print(output)

b'Hello world!'


In [6]:
# A is a 0-dimension int32 tensor

A=tf.constant(1234)

#B is a 1-dimension int32 tensor

B=tf.constant([123,456,789])


#C is a 2-dimension int32 tensor

C=tf.constant([[123,456,789], [222,333,444]])

In [7]:
with tf.Graph().as_default():
    c1=tf.constant(4,dtype=tf.float64,name='c')
    c2=tf.constant(4,dtype=tf.int32,name='c')
    c3=tf.constant(4,dtype=tf.int32,name='c')
print(c1.name)
print(c2.name)
print(c3.name)

c:0
c_1:0
c_2:0


In [8]:
with tf.Graph().as_default():
    c1 = tf.constant(4,dtype=tf.float64,name='c')
with tf.name_scope('prefix_name'):
    c2=tf.constant(4,dtype=tf.int32,name='c')
    c3=tf.constant(4,dtype=tf.float64,name='c')
print(c1.name)
print(c2.name)
print(c3.name)
print(c1)

c:0
prefix_name/c:0
prefix_name/c_1:0
Tensor("c:0", shape=(), dtype=float64)


In [9]:
pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.


In [10]:
import tensorflow as tf

#create TensorFlow object called tensor

hello_constant=tf.constant('Hello World!')

In [11]:
with tf.compat.v1.Session() as sess:
    #Run the tf.constant operation in the session
    output=sess.run(hello_constant)
    print(output)

b'Hello World!'


In [12]:
C= tf.constant([ [123,456,789], [222,333,444] ])

sess = tf.compat.v1.Session()

sess.run(C)

array([[123, 456, 789],
       [222, 333, 444]])

# NOTE ANY PLACE YOU SEE TF.SESSION USE TF.COMPAT.V1.SESSION 

In [13]:
init_val = tf.random.normal((1,5),0,1)

var=tf.Variable(init_val, name='var')

print("pre run:\n{}".format(var))
init=tf.compat.v1.global_variables_initializer()



pre run:
<tf.Variable 'var:0' shape=(1, 5) dtype=float32>


In [14]:
with tf.compat.v1.Session() as sess:
    sess.run(init)
    post_var=sess.run(var)
print("\n post run:\n{}".format(post_var))
    


 post run:
[[-1.0369499  -0.48692787 -0.7686685  -1.7755388  -1.2844329 ]]


# OR

In [15]:
init_val = tf.random.normal((1,5),0,1)

var=tf.Variable(init_val, name='var')

print("pre run:\n{}".format(var))
init=tf.compat.v1.global_variables_initializer()


with tf.compat.v1.Session() as sess:
    sess.run(init)
    post_var=sess.run(var)
print("\n post run:\n{}".format(post_var))
    


pre run:
<tf.Variable 'var_1:0' shape=(1, 5) dtype=float32>

 post run:
[[ 0.1963252  -0.7479768   0.6067028   0.5022942  -0.06952149]]


In [16]:
X= tf.compat.v1.placeholder(tf.string)

with tf.compat.v1.Session() as sess:
    output=sess.run(X, feed_dict={X: 'test'})
    print(output)

test


In [17]:
x= tf.compat.v1.placeholder('float',None)
y=x**2

with tf.compat.v1.Session() as session:
    result=session.run(y, feed_dict={x: [1,2,3]})
    print(result)

[1. 4. 9.]


In [18]:
#Check for Data Types


x=tf.add(5,2) #7
with tf.compat.v1.Session() as sess:
    output = sess.run(x)
    print(output)

7


In [19]:
x=tf.subtract(10,4) #6

y=tf.multiply(2,5) #10


#CHECK THE NOTE

In [20]:
x

<tf.Tensor 'Sub_1:0' shape=() dtype=int32>

In [21]:
c=tf.subtract(tf.cast(tf.constant(2.0), tf.int32), tf.constant(1))

with tf.compat.v1.Session() as sess:
    output=sess.run(c)
    print(output)
    
#Note in place of the subtract you can you multiply and others to execute your functions

1


In [22]:
x=tf.constant(10)
y=tf.constant(2)
z=tf.subtract(tf.divide(x, y),1)

with tf.compat.v1.Session() as sess:
    output=sess.run(z)
    print(output)

4.0


Tensorflow Linear function

tf.truncated_normal()

In [23]:
n_features =120
n_labels = 5
weights = tf.Variable(tf.compat.v1.random.truncated_normal((n_features, n_labels)))

weights

<tf.Variable 'Variable:0' shape=(120, 5) dtype=float32>

tf.Zeros()

In [25]:
#Initialising this as normal zero

n_labels

bias=tf.Variable(tf.zeros(n_labels))

In [30]:
import tensorflow as tf

#Create operations, Tensors, etc (using the default graph)

a = tf.add(2, 5)
b = tf.multiply(a, 3)

# Start up a Session using the default graph

sess = tf.compat.v1.Session()

# Define a dictionary that says to replace the value of a with 15

replace_dict = {a: 15}

#Run the Session, passing in replace_dict as the value to feed_dict

output = sess.run(b, feed_dict=replace_dict)

print(output)

45


# BUILDING OF SOFTMAX

In [32]:
x = tf.nn.softmax([2.0, 1.0, 0.2])

x

<tf.Tensor 'Softmax_1:0' shape=(3,) dtype=float32>

In [33]:
import tensorflow as tf

def run_2():
    output = None 
    logit_data = [19,354,354,45,354,54]
    logits = tf.compat.v1.placeholder(tf.float32)
    
    #Calculate the softmax of the logit
    softmax = tf.nn.softmax(logits)
    
    
    with tf.compat.v1.Session() as sess:
        #Feed inthe logit data
        output = sess.run(softmax, feed_dict={logits: logit_data})
    return output
print(run_2())

[0.         0.33333334 0.33333334 0.         0.33333334 0.        ]


# TO CREATE CROSS ENTROPY

THIS CAN BE DONE USING 

tf.reduce_sum()

tf.log()

In [42]:
x = tf.reduce_sum([1,2,3,4,5])  #15



In [43]:
# FOR NATURAL LOG

l = tf.compat.v1.log(100.0)  #4.60517

l

<tf.Tensor 'Log_4:0' shape=() dtype=float32>

In [44]:
#YOU CAN TRY THIS PATTERN AS WELL, IT WILL WORK

l = tf.math.log(100.0)  #4.60517

l

<tf.Tensor 'Log_5:0' shape=() dtype=float32>

In [47]:
import tensorflow as tf

softmax_data = [0.7, 0.2, 0.1]
one_hot_data = [1.0, 0.0, 0.0]


softmax = tf.compat.v1.placeholder(tf.float32)
one_hot = tf.compat.v1.placeholder(tf.float32)
#print cross entropy from Session

cross_entropy = -tf.reduce_sum(tf.multiply(one_hot, tf.math.log(softmax)))

with tf.compat.v1.Session() as session:
    output=session.run(cross_entropy, feed_dict={one_hot:one_hot_data, softmax: softmax_data})
    print(output)

0.35667497
